print("-----------------------------begin------------------------------------------------------")
print("success")
print("if success,i will go home!")
print("\n成功")
print("if success,i will go home!")
print("-----------------------------end------------------------------------------------------")